/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package liuyx.kotlin.coursera

class App {
    val greeting = """
        Welcome to your banking system.
        What type of account wuld you like to create?
        1. Debit account
        2. credit account
        3. Checking account
        Choose an option (1, 2 or 3)
    """.trimIndent()
}

fun main() {
    println(App().greeting)

    while (true) {
        val option = readln().toInt()
        println("The selected option is $option")
    }
}
